# Generated by Django 3.1.1 on 2020-10-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('employeeID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[(1, '男'), (2, '女')], max_length=20, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('tel', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(blank=True, choices=[(1, '男'), (2, '女')], max_length=20, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('credit', models.FloatField(default=0)),
                ('level', models.CharField(choices=[('RM', 'RegularMembers'), ('SM', 'SilverMembers'), ('GM', 'GoldMembers'), ('DM', 'DiamondMembers')], default='RM', max_length=20)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('taxID', models.CharField(max_length=20)),
                ('invoice_type', models.CharField(choices=[('Cor', '企业的'), ('Per', '个人的')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=100)),
                ('bank_account', models.CharField(max_length=30)),
                ('bank_address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('star_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('review_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'oder_review',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('credit_needed', models.FloatField()),
                ('sales', models.FloatField()),
                ('stock', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticketID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ticket_name', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ticket_type', models.CharField(choices=[('DZ', '打折券'), ('MJ', '满减券')], max_length=20)),
                ('discount', models.FloatField()),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('ticket_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.product')),
            ],
            options={
                'db_table': 'Shopping_Cart',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('total_money', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('credit_increment', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.client')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gasstation.invoice')),
                ('products', models.ManyToManyField(through='gasstation.OderProduct', to='gasstation.Product')),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gasstation.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='oderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.order'),
        ),
        migrations.AddField(
            model_name='oderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.product'),
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(through='gasstation.ShoppingCart', to='gasstation.Product'),
        ),
        migrations.CreateModel(
            name='AdministratorTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.administrator')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='AdministratorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.administrator')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdministratorClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.administrator')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.client')),
            ],
        ),
        migrations.AddField(
            model_name='administrator',
            name='clients',
            field=models.ManyToManyField(through='gasstation.AdministratorClient', to='gasstation.Client'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='products',
            field=models.ManyToManyField(through='gasstation.AdministratorProduct', to='gasstation.Product'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='tickets',
            field=models.ManyToManyField(through='gasstation.AdministratorTicket', to='gasstation.Ticket'),
        ),
    ]
