# Generated by Django 3.1.1 on 2020-10-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasstation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='pwd',
            field=models.CharField(default='jiayoubao666', max_length=20),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
